Numpy vs Lists  
    - Faster to read less bytes of memory.   
    - No type checking when iterating through objects.  
    - Numpy  has contigous memory unlike Lists.   

In [3]:
import numpy as np

a = np.array([1,3,5])
b = np.array([2,3,5])
b*a

array([ 2,  9, 25])

In [4]:
a = np.array([1,2,3]) #1-D array    

In [5]:
b = np.array([[8,7,6,7,8],[1,4,6,2,9],[4,7,8,9,2]])
b

array([[8, 7, 6, 7, 8],
       [1, 4, 6, 2, 9],
       [4, 7, 8, 9, 2]])

In [8]:
b = np.array([[8,7,6,7,8],[1,4,6,2,9]])
b

array([[8, 7, 6, 7, 8],
       [1, 4, 6, 2, 9]])

In [27]:
a = np.array([1, 2, 3])  # 1-D array
b = np.array([[8, 7, 6, 7, 8], [1, 4, 6, 2, 9]])  # 2-D array
s = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 3-D array
a,b,s

(array([1, 2, 3]),
 array([[8, 7, 6, 7, 8],
        [1, 4, 6, 2, 9]]),
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]))

In [29]:
#the number of axes (dimensions) of the array.
b.ndim, a.ndim, s.ndim

(2, 1, 3)

In [28]:
#the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension
b.shape, a.shape, s.shape

((2, 5), (3,), (2, 2, 2))

In [30]:
#the total number of elements of the array. This is equal to the 
# product of the elements of shape.

b.size, a.size, s.size

(10, 3, 8)

In [31]:
b.dtype, a.dtype, s.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [32]:
b.dtype.itemsize, a.dtype.itemsize, s.dtype.itemsize

(8, 8, 8)

In [33]:
e = np.array([1.1, 2.2, 3.3], dtype=float)  # float array
f = np.array([True, False, True], dtype=bool)  # boolean array
g = np.array(['a', 'b', 'c'], dtype=str)  # string array

e, f, g

(array([1.1, 2.2, 3.3]),
 array([ True, False,  True]),
 array(['a', 'b', 'c'], dtype='<U1'))

In [36]:
e.dtype, f.dtype, g.dtype

(dtype('float64'), dtype('bool'), dtype('<U1'))

In [38]:
k = np.arange(20).reshape(4,5)
k

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
k.shape

(4, 5)

In [40]:
k.dtype.name

'int64'