Numpy vs Lists
    - Faster to read less bytes of memory. 
    - No type checking when iterating through objects.
    - Numpy  has contigous memory unlike Lists. 

In [1]:
import numpy as np

a = np.array([1,3,5])
b = np.array([2,3,5])
b*a

array([ 2,  9, 25])

In [2]:
a = np.array([1,2,3]) #1-D array    

In [7]:
b = np.array([[8,7,6,7,8],[1,4,6,2,9],[4,7,8,9,2]])
b

array([[8, 7, 6, 7, 8],
       [1, 4, 6, 2, 9],
       [4, 7, 8, 9, 2]])

In [8]:
b = np.array([[8,7,6,7,8],[1,4,6,2,9]])
b

array([[8, 7, 6, 7, 8],
       [1, 4, 6, 2, 9]])