## NumPy Crash Course

In [2]:
import numpy as np

In [4]:
np.__version__

'2.2.0'

In [6]:
#creating arrays

lst = [0,1,2,3,4,5]
lst

[0, 1, 2, 3, 4, 5]

In [8]:
type(lst)

list

In [9]:
arr = np.array(lst)

In [10]:
arr

array([0, 1, 2, 3, 4, 5])

In [11]:
type(arr)

numpy.ndarray

In [12]:
type(lst)

list

In [ ]:
np. #we learn important function 

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
np.arange(3.0)

array([0., 1., 2.])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(10,230)

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
       101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
       179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 19

In [18]:
np.arange(20,10)

array([], dtype=int64)

In [19]:
np.arange(30, 10 , -4)

array([30, 26, 22, 18, 14])

In [20]:
np.arange(10,10)

array([], dtype=int64)

In [21]:
np.arange(14,46,2)

array([14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44])

In [22]:
np.arange(0,80,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78])

In [23]:
np.arange(10,30,4,5)

TypeError: Cannot interpret '5' as a data type

In [25]:
np.zeros(3)

array([0., 0., 0.])

In [26]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [28]:
np.zeros((3,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [30]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [34]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n,dtype = int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [35]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [36]:
n

(6, 7)

In [38]:
n1

(6, 8)

In [39]:
np.ones(3)

array([1., 1., 1.])

In [40]:
np.ones(4, dtype = int)

array([1, 1, 1, 1])

In [41]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [42]:
np.ones((5,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [43]:
np.ones((6,10), dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [44]:
np.three(4)

AttributeError: module 'numpy' has no attribute 'three'

In [45]:
np.two(4)

AttributeError: module 'numpy' has no attribute 'two'

In [46]:
range(5)

range(0, 5)

In [48]:
r = range(5)
r

range(0, 5)

In [52]:
np.random.rand(2,10)

array([[0.31587943, 0.35833224, 0.01357009, 0.12674541, 0.12098634,
        0.02629827, 0.21296927, 0.57708019, 0.08224757, 0.98221641],
       [0.50244408, 0.31088732, 0.15155044, 0.16762727, 0.42115369,
        0.33457377, 0.98443459, 0.24393428, 0.82658878, 0.45653738]])

In [54]:
np.random.randint(2,10, (4,5))

array([[6, 4, 8, 5, 2],
       [3, 9, 9, 9, 4],
       [5, 6, 9, 9, 4],
       [7, 9, 4, 3, 6]], dtype=int32)

In [55]:
np.random.randint(10,40,(6,5))

array([[30, 24, 34, 19, 20],
       [17, 19, 35, 27, 31],
       [24, 21, 12, 29, 16],
       [12, 12, 16, 38, 19],
       [25, 14, 30, 29, 35],
       [28, 12, 22, 24, 34]], dtype=int32)

In [57]:
np.random.randint(0,50,10)

array([10, 18, 46, 30,  3,  7, 49, 45, 17,  7], dtype=int32)

In [58]:
np.random.rand(3)

array([0.64943094, 0.64440695, 0.63449414])

In [59]:
np.random.randint(30,20,10)

ValueError: low >= high

In [60]:
np.random.rand(4)

array([0.24711522, 0.48017497, 0.22125067, 0.68626444])

In [61]:
np.random.randint(-30, 20, 10)

array([  9,  10,  -8, -10, -18, -13, -24,  -5,  11,   0], dtype=int32)

In [62]:
np.random.randint(20,30,10)

array([24, 28, 23, 23, 20, 22, 22, 21, 21, 21], dtype=int32)

In [63]:
np.random.randint(10,40,(4,4))

array([[35, 35, 10, 10],
       [28, 27, 24, 12],
       [35, 23, 24, 37],
       [26, 25, 24, 23]], dtype=int32)

In [64]:
np.random.randint(10,40,(10,10))

array([[23, 34, 21, 18, 37, 30, 21, 38, 33, 38],
       [22, 14, 27, 15, 13, 21, 32, 31, 25, 28],
       [13, 10, 33, 17, 38, 22, 14, 23, 39, 36],
       [20, 24, 36, 37, 30, 34, 28, 33, 36, 25],
       [29, 32, 32, 34, 35, 12, 18, 22, 18, 36],
       [38, 18, 19, 28, 33, 17, 30, 33, 12, 39],
       [35, 37, 23, 24, 37, 28, 30, 12, 16, 24],
       [24, 20, 23, 30, 21, 14, 14, 18, 33, 16],
       [21, 34, 32, 22, 15, 16, 19, 20, 29, 37],
       [23, 27, 28, 16, 32, 19, 11, 31, 10, 36]], dtype=int32)

In [66]:
np.random.randint(1,100,(12,12))

array([[16, 49, 99, 96, 72, 91, 62, 64, 39, 87, 23, 18],
       [40, 24, 71, 61, 50,  2, 18, 75, 93, 80, 20, 30],
       [78, 76, 30, 74, 22, 98, 53, 93, 51, 62,  9, 56],
       [14, 52, 57,  6,  2, 82, 56, 24, 24, 26, 37, 32],
       [62, 24, 48, 65,  3, 23, 36, 49, 35,  1, 32, 35],
       [51, 18,  7, 93, 98, 89, 57, 89, 23, 61, 14, 88],
       [59, 90, 63, 29, 73, 99, 54, 74, 47, 54, 12, 82],
       [58, 83, 19, 48, 43, 89, 11, 15, 42, 91,  2, 16],
       [19, 76, 37, 48,  5,  5, 22, 36, 77, 18, 88, 95],
       [84, 49, 38, 71,  6, 23, 52, 17, 71, 24, 50, 14],
       [25, 99, 15, 57, 42, 92, 51, 14, 60, 29, 53, 17],
       [25, 49,  7, 93, 84, 95, 65, 27, 66, 84, 84, 28]], dtype=int32)

In [67]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [68]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
b = np.random.randint(10,20,(5,4))
b

array([[16, 14, 17, 18],
       [19, 10, 11, 11],
       [12, 10, 13, 13],
       [17, 19, 17, 13],
       [14, 10, 15, 10]], dtype=int32)

In [71]:
type(b)

numpy.ndarray

In [72]:
b

array([[16, 14, 17, 18],
       [19, 10, 11, 11],
       [12, 10, 13, 13],
       [17, 19, 17, 13],
       [14, 10, 15, 10]], dtype=int32)

In [73]:
b[:]

array([[16, 14, 17, 18],
       [19, 10, 11, 11],
       [12, 10, 13, 13],
       [17, 19, 17, 13],
       [14, 10, 15, 10]], dtype=int32)

In [74]:
b[1:3]

array([[19, 10, 11, 11],
       [12, 10, 13, 13]], dtype=int32)

In [75]:
b

array([[16, 14, 17, 18],
       [19, 10, 11, 11],
       [12, 10, 13, 13],
       [17, 19, 17, 13],
       [14, 10, 15, 10]], dtype=int32)

In [76]:
b[1,2]

np.int32(11)

In [77]:
b[1,3]

np.int32(11)

In [78]:
b[1,-1]

np.int32(11)

In [79]:
b[2:3]

array([[12, 10, 13, 13]], dtype=int32)

In [80]:
b[0:-2]

array([[16, 14, 17, 18],
       [19, 10, 11, 11],
       [12, 10, 13, 13]], dtype=int32)

In [81]:
b[0,2]

np.int32(17)

In [82]:
b[-5,-3]

np.int32(14)

In [83]:
b[-4,2]

np.int32(11)

In [84]:
np.random.randint(10,20,(4,4))

array([[11, 12, 16, 15],
       [14, 14, 10, 16],
       [16, 19, 16, 15],
       [17, 12, 10, 12]], dtype=int32)

## Operations

In [85]:
a = np.random.randint(10,20,10)
a

array([13, 10, 14, 17, 10, 12, 18, 13, 13, 14], dtype=int32)

In [86]:
id(a)

2064467023344

In [87]:
arr

array([0, 1, 2, 3, 4, 5])

In [89]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[ 7, 20, 60, 13, 80,  2, 49, 90, 12, 71],
       [15, 91, 70, 37, 45, 95, 74, 90, 22, 41],
       [69,  5, 66, 90, 36, 73, 24,  9, 44,  2],
       [60,  6, 40, 28, 74, 76, 75, 71, 25, 45],
       [85, 86, 56, 86, 21, 28, 10, 87, 32, 93],
       [57, 37, 28, 73, 81, 28, 88, 52, 63, 53],
       [61, 98, 13, 50, 69, 67, 15,  8, 83, 12],
       [93, 95, 93, 44, 41, 57, 18, 56, 81, 46],
       [93, 99, 94, 47, 33, 59, 61, 28,  8, 16],
       [66, 85, 35, 54, 36, 38, 88, 13, 47, 15]], dtype=int32)

In [90]:
arr

array([0, 1, 2, 3, 4, 5])

In [91]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [92]:
arr[:4]

array([0, 1, 2, 3])

In [93]:
arr2[:]

array([[ 7, 20, 60, 13, 80,  2, 49, 90, 12, 71],
       [15, 91, 70, 37, 45, 95, 74, 90, 22, 41],
       [69,  5, 66, 90, 36, 73, 24,  9, 44,  2],
       [60,  6, 40, 28, 74, 76, 75, 71, 25, 45],
       [85, 86, 56, 86, 21, 28, 10, 87, 32, 93],
       [57, 37, 28, 73, 81, 28, 88, 52, 63, 53],
       [61, 98, 13, 50, 69, 67, 15,  8, 83, 12],
       [93, 95, 93, 44, 41, 57, 18, 56, 81, 46],
       [93, 99, 94, 47, 33, 59, 61, 28,  8, 16],
       [66, 85, 35, 54, 36, 38, 88, 13, 47, 15]], dtype=int32)

In [94]:
arr2[0:5]

array([[ 7, 20, 60, 13, 80,  2, 49, 90, 12, 71],
       [15, 91, 70, 37, 45, 95, 74, 90, 22, 41],
       [69,  5, 66, 90, 36, 73, 24,  9, 44,  2],
       [60,  6, 40, 28, 74, 76, 75, 71, 25, 45],
       [85, 86, 56, 86, 21, 28, 10, 87, 32, 93]], dtype=int32)

In [95]:
arr2

array([[ 7, 20, 60, 13, 80,  2, 49, 90, 12, 71],
       [15, 91, 70, 37, 45, 95, 74, 90, 22, 41],
       [69,  5, 66, 90, 36, 73, 24,  9, 44,  2],
       [60,  6, 40, 28, 74, 76, 75, 71, 25, 45],
       [85, 86, 56, 86, 21, 28, 10, 87, 32, 93],
       [57, 37, 28, 73, 81, 28, 88, 52, 63, 53],
       [61, 98, 13, 50, 69, 67, 15,  8, 83, 12],
       [93, 95, 93, 44, 41, 57, 18, 56, 81, 46],
       [93, 99, 94, 47, 33, 59, 61, 28,  8, 16],
       [66, 85, 35, 54, 36, 38, 88, 13, 47, 15]], dtype=int32)

In [96]:
arr2[1,4]

np.int32(45)

In [97]:
arr2[-5,-5]

np.int32(28)

In [98]:
arr2[::-1]

array([[66, 85, 35, 54, 36, 38, 88, 13, 47, 15],
       [93, 99, 94, 47, 33, 59, 61, 28,  8, 16],
       [93, 95, 93, 44, 41, 57, 18, 56, 81, 46],
       [61, 98, 13, 50, 69, 67, 15,  8, 83, 12],
       [57, 37, 28, 73, 81, 28, 88, 52, 63, 53],
       [85, 86, 56, 86, 21, 28, 10, 87, 32, 93],
       [60,  6, 40, 28, 74, 76, 75, 71, 25, 45],
       [69,  5, 66, 90, 36, 73, 24,  9, 44,  2],
       [15, 91, 70, 37, 45, 95, 74, 90, 22, 41],
       [ 7, 20, 60, 13, 80,  2, 49, 90, 12, 71]], dtype=int32)

In [99]:
arr[::-2]

array([5, 3, 1])

In [100]:
arr[::-3]

array([5, 2])

In [102]:
arr2[:-3]

array([[ 7, 20, 60, 13, 80,  2, 49, 90, 12, 71],
       [15, 91, 70, 37, 45, 95, 74, 90, 22, 41],
       [69,  5, 66, 90, 36, 73, 24,  9, 44,  2],
       [60,  6, 40, 28, 74, 76, 75, 71, 25, 45],
       [85, 86, 56, 86, 21, 28, 10, 87, 32, 93],
       [57, 37, 28, 73, 81, 28, 88, 52, 63, 53],
       [61, 98, 13, 50, 69, 67, 15,  8, 83, 12]], dtype=int32)

In [103]:
arr.max()

np.int64(5)

In [104]:
arr.min()

np.int64(0)

In [105]:
arr.mean()

np.float64(2.5)

AttributeError: 'numpy.ndarray' object has no attribute 'median'