## NumPy Crash Course

In [21]:
import numpy as np

In [22]:
np.__version__

'2.2.0'

In [23]:
#creating arrays

lst = [0,1,2,3,4,5]
lst

[0, 1, 2, 3, 4, 5]

In [24]:
type(lst)

list

In [25]:
arr = np.array(lst)

In [26]:
arr

array([0, 1, 2, 3, 4, 5])

In [27]:
type(arr)

numpy.ndarray

In [28]:
type(lst)

list

In [29]:
np. #we learn important function 

SyntaxError: invalid syntax (4074483282.py, line 1)

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
np.arange(3.0)

array([0., 1., 2.])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(10,230)

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
       101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
       179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 19

In [18]:
np.arange(20,10)

array([], dtype=int64)

In [19]:
np.arange(30, 10 , -4)

array([30, 26, 22, 18, 14])

In [20]:
np.arange(10,10)

array([], dtype=int64)

In [21]:
np.arange(14,46,2)

array([14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44])

In [22]:
np.arange(0,80,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78])

In [23]:
np.arange(10,30,4,5)

TypeError: Cannot interpret '5' as a data type

In [25]:
np.zeros(3)

array([0., 0., 0.])

In [26]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [28]:
np.zeros((3,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [30]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [34]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n,dtype = int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [35]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [36]:
n

(6, 7)

In [38]:
n1

(6, 8)

In [39]:
np.ones(3)

array([1., 1., 1.])

In [40]:
np.ones(4, dtype = int)

array([1, 1, 1, 1])

In [41]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [42]:
np.ones((5,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [43]:
np.ones((6,10), dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [44]:
np.three(4)

AttributeError: module 'numpy' has no attribute 'three'

In [45]:
np.two(4)

AttributeError: module 'numpy' has no attribute 'two'

In [46]:
range(5)

range(0, 5)

In [48]:
r = range(5)
r

range(0, 5)

In [52]:
np.random.rand(2,10)

array([[0.31587943, 0.35833224, 0.01357009, 0.12674541, 0.12098634,
        0.02629827, 0.21296927, 0.57708019, 0.08224757, 0.98221641],
       [0.50244408, 0.31088732, 0.15155044, 0.16762727, 0.42115369,
        0.33457377, 0.98443459, 0.24393428, 0.82658878, 0.45653738]])

In [54]:
np.random.randint(2,10, (4,5))

array([[6, 4, 8, 5, 2],
       [3, 9, 9, 9, 4],
       [5, 6, 9, 9, 4],
       [7, 9, 4, 3, 6]], dtype=int32)

In [55]:
np.random.randint(10,40,(6,5))

array([[30, 24, 34, 19, 20],
       [17, 19, 35, 27, 31],
       [24, 21, 12, 29, 16],
       [12, 12, 16, 38, 19],
       [25, 14, 30, 29, 35],
       [28, 12, 22, 24, 34]], dtype=int32)

In [57]:
np.random.randint(0,50,10)

array([10, 18, 46, 30,  3,  7, 49, 45, 17,  7], dtype=int32)

In [58]:
np.random.rand(3)

array([0.64943094, 0.64440695, 0.63449414])

In [59]:
np.random.randint(30,20,10)

ValueError: low >= high

In [60]:
np.random.rand(4)

array([0.24711522, 0.48017497, 0.22125067, 0.68626444])

In [61]:
np.random.randint(-30, 20, 10)

array([  9,  10,  -8, -10, -18, -13, -24,  -5,  11,   0], dtype=int32)

In [62]:
np.random.randint(20,30,10)

array([24, 28, 23, 23, 20, 22, 22, 21, 21, 21], dtype=int32)

In [63]:
np.random.randint(10,40,(4,4))

array([[35, 35, 10, 10],
       [28, 27, 24, 12],
       [35, 23, 24, 37],
       [26, 25, 24, 23]], dtype=int32)

In [64]:
np.random.randint(10,40,(10,10))

array([[23, 34, 21, 18, 37, 30, 21, 38, 33, 38],
       [22, 14, 27, 15, 13, 21, 32, 31, 25, 28],
       [13, 10, 33, 17, 38, 22, 14, 23, 39, 36],
       [20, 24, 36, 37, 30, 34, 28, 33, 36, 25],
       [29, 32, 32, 34, 35, 12, 18, 22, 18, 36],
       [38, 18, 19, 28, 33, 17, 30, 33, 12, 39],
       [35, 37, 23, 24, 37, 28, 30, 12, 16, 24],
       [24, 20, 23, 30, 21, 14, 14, 18, 33, 16],
       [21, 34, 32, 22, 15, 16, 19, 20, 29, 37],
       [23, 27, 28, 16, 32, 19, 11, 31, 10, 36]], dtype=int32)

In [66]:
np.random.randint(1,100,(12,12))

array([[16, 49, 99, 96, 72, 91, 62, 64, 39, 87, 23, 18],
       [40, 24, 71, 61, 50,  2, 18, 75, 93, 80, 20, 30],
       [78, 76, 30, 74, 22, 98, 53, 93, 51, 62,  9, 56],
       [14, 52, 57,  6,  2, 82, 56, 24, 24, 26, 37, 32],
       [62, 24, 48, 65,  3, 23, 36, 49, 35,  1, 32, 35],
       [51, 18,  7, 93, 98, 89, 57, 89, 23, 61, 14, 88],
       [59, 90, 63, 29, 73, 99, 54, 74, 47, 54, 12, 82],
       [58, 83, 19, 48, 43, 89, 11, 15, 42, 91,  2, 16],
       [19, 76, 37, 48,  5,  5, 22, 36, 77, 18, 88, 95],
       [84, 49, 38, 71,  6, 23, 52, 17, 71, 24, 50, 14],
       [25, 99, 15, 57, 42, 92, 51, 14, 60, 29, 53, 17],
       [25, 49,  7, 93, 84, 95, 65, 27, 66, 84, 84, 28]], dtype=int32)

In [67]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [68]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
b = np.random.randint(10,20,(5,4))
b

array([[16, 14, 17, 18],
       [19, 10, 11, 11],
       [12, 10, 13, 13],
       [17, 19, 17, 13],
       [14, 10, 15, 10]], dtype=int32)

In [71]:
type(b)

numpy.ndarray

In [72]:
b

array([[16, 14, 17, 18],
       [19, 10, 11, 11],
       [12, 10, 13, 13],
       [17, 19, 17, 13],
       [14, 10, 15, 10]], dtype=int32)

In [73]:
b[:]

array([[16, 14, 17, 18],
       [19, 10, 11, 11],
       [12, 10, 13, 13],
       [17, 19, 17, 13],
       [14, 10, 15, 10]], dtype=int32)

In [74]:
b[1:3]

array([[19, 10, 11, 11],
       [12, 10, 13, 13]], dtype=int32)

In [75]:
b

array([[16, 14, 17, 18],
       [19, 10, 11, 11],
       [12, 10, 13, 13],
       [17, 19, 17, 13],
       [14, 10, 15, 10]], dtype=int32)

In [76]:
b[1,2]

np.int32(11)

In [77]:
b[1,3]

np.int32(11)

In [78]:
b[1,-1]

np.int32(11)

In [79]:
b[2:3]

array([[12, 10, 13, 13]], dtype=int32)

In [80]:
b[0:-2]

array([[16, 14, 17, 18],
       [19, 10, 11, 11],
       [12, 10, 13, 13]], dtype=int32)

In [81]:
b[0,2]

np.int32(17)

In [82]:
b[-5,-3]

np.int32(14)

In [83]:
b[-4,2]

np.int32(11)

In [84]:
np.random.randint(10,20,(4,4))

array([[11, 12, 16, 15],
       [14, 14, 10, 16],
       [16, 19, 16, 15],
       [17, 12, 10, 12]], dtype=int32)

## Operations

In [85]:
a = np.random.randint(10,20,10)
a

array([13, 10, 14, 17, 10, 12, 18, 13, 13, 14], dtype=int32)

In [86]:
id(a)

2064467023344

In [87]:
arr

array([0, 1, 2, 3, 4, 5])

In [31]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[40, 45, 87, 34, 29, 92, 45, 22, 64, 36],
       [21, 49, 24, 35,  9, 83, 58, 54, 14, 83],
       [76, 56, 23, 98, 56, 31, 26, 72, 81, 25],
       [46, 70, 69, 19,  5, 89, 27, 10, 25, 28],
       [35, 93, 62, 87, 26, 61, 76, 67, 98, 50],
       [14, 58, 91, 49, 57, 84,  1, 54, 42, 51],
       [ 4, 86, 99, 31, 21, 18, 22, 42, 60, 64],
       [45, 40, 23, 94,  1,  8, 98, 82, 53, 54],
       [66, 62, 42, 89, 50, 98, 51, 84, 65, 86],
       [40,  2, 11, 27, 37, 31, 21,  0, 43, 37]], dtype=int32)

In [32]:
arr

array([0, 1, 2, 3, 4, 5])

In [33]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [34]:
arr[:4]

array([0, 1, 2, 3])

In [35]:
arr2[:]

array([[40, 45, 87, 34, 29, 92, 45, 22, 64, 36],
       [21, 49, 24, 35,  9, 83, 58, 54, 14, 83],
       [76, 56, 23, 98, 56, 31, 26, 72, 81, 25],
       [46, 70, 69, 19,  5, 89, 27, 10, 25, 28],
       [35, 93, 62, 87, 26, 61, 76, 67, 98, 50],
       [14, 58, 91, 49, 57, 84,  1, 54, 42, 51],
       [ 4, 86, 99, 31, 21, 18, 22, 42, 60, 64],
       [45, 40, 23, 94,  1,  8, 98, 82, 53, 54],
       [66, 62, 42, 89, 50, 98, 51, 84, 65, 86],
       [40,  2, 11, 27, 37, 31, 21,  0, 43, 37]], dtype=int32)

In [36]:
arr2[0:5]

array([[40, 45, 87, 34, 29, 92, 45, 22, 64, 36],
       [21, 49, 24, 35,  9, 83, 58, 54, 14, 83],
       [76, 56, 23, 98, 56, 31, 26, 72, 81, 25],
       [46, 70, 69, 19,  5, 89, 27, 10, 25, 28],
       [35, 93, 62, 87, 26, 61, 76, 67, 98, 50]], dtype=int32)

In [37]:
arr2

array([[40, 45, 87, 34, 29, 92, 45, 22, 64, 36],
       [21, 49, 24, 35,  9, 83, 58, 54, 14, 83],
       [76, 56, 23, 98, 56, 31, 26, 72, 81, 25],
       [46, 70, 69, 19,  5, 89, 27, 10, 25, 28],
       [35, 93, 62, 87, 26, 61, 76, 67, 98, 50],
       [14, 58, 91, 49, 57, 84,  1, 54, 42, 51],
       [ 4, 86, 99, 31, 21, 18, 22, 42, 60, 64],
       [45, 40, 23, 94,  1,  8, 98, 82, 53, 54],
       [66, 62, 42, 89, 50, 98, 51, 84, 65, 86],
       [40,  2, 11, 27, 37, 31, 21,  0, 43, 37]], dtype=int32)

In [38]:
arr2[1,4]

np.int32(9)

In [39]:
arr2[-5,-5]

np.int32(84)

In [40]:
arr2[::-1]

array([[40,  2, 11, 27, 37, 31, 21,  0, 43, 37],
       [66, 62, 42, 89, 50, 98, 51, 84, 65, 86],
       [45, 40, 23, 94,  1,  8, 98, 82, 53, 54],
       [ 4, 86, 99, 31, 21, 18, 22, 42, 60, 64],
       [14, 58, 91, 49, 57, 84,  1, 54, 42, 51],
       [35, 93, 62, 87, 26, 61, 76, 67, 98, 50],
       [46, 70, 69, 19,  5, 89, 27, 10, 25, 28],
       [76, 56, 23, 98, 56, 31, 26, 72, 81, 25],
       [21, 49, 24, 35,  9, 83, 58, 54, 14, 83],
       [40, 45, 87, 34, 29, 92, 45, 22, 64, 36]], dtype=int32)

In [41]:
arr[::-2]

array([5, 3, 1])

In [42]:
arr[::-3]

array([5, 2])

In [43]:
arr2[:-3]

array([[40, 45, 87, 34, 29, 92, 45, 22, 64, 36],
       [21, 49, 24, 35,  9, 83, 58, 54, 14, 83],
       [76, 56, 23, 98, 56, 31, 26, 72, 81, 25],
       [46, 70, 69, 19,  5, 89, 27, 10, 25, 28],
       [35, 93, 62, 87, 26, 61, 76, 67, 98, 50],
       [14, 58, 91, 49, 57, 84,  1, 54, 42, 51],
       [ 4, 86, 99, 31, 21, 18, 22, 42, 60, 64]], dtype=int32)

In [44]:
arr.max()

np.int64(5)

In [45]:
arr.min()

np.int64(0)

In [46]:
arr.mean()

np.float64(2.5)

In [47]:
from numpy import *
median(arr)

np.float64(2.5)

In [48]:
#finding median and mode without the inbuilt functions

l = len(arr)

if len(arr) % 2 == 0:
   print("median : ", (arr[l//2] + arr[l//2 - 1])/2)
else:
    print("median : ", arr[l//2]) 

median :  2.5


In [50]:
arr2

array([[40, 45, 87, 34, 29, 92, 45, 22, 64, 36],
       [21, 49, 24, 35,  9, 83, 58, 54, 14, 83],
       [76, 56, 23, 98, 56, 31, 26, 72, 81, 25],
       [46, 70, 69, 19,  5, 89, 27, 10, 25, 28],
       [35, 93, 62, 87, 26, 61, 76, 67, 98, 50],
       [14, 58, 91, 49, 57, 84,  1, 54, 42, 51],
       [ 4, 86, 99, 31, 21, 18, 22, 42, 60, 64],
       [45, 40, 23, 94,  1,  8, 98, 82, 53, 54],
       [66, 62, 42, 89, 50, 98, 51, 84, 65, 86],
       [40,  2, 11, 27, 37, 31, 21,  0, 43, 37]], dtype=int32)

In [55]:
for i in arr2:
    print(i)

[40 45 87 34 29 92 45 22 64 36]
[21 49 24 35  9 83 58 54 14 83]
[76 56 23 98 56 31 26 72 81 25]
[46 70 69 19  5 89 27 10 25 28]
[35 93 62 87 26 61 76 67 98 50]
[14 58 91 49 57 84  1 54 42 51]
[ 4 86 99 31 21 18 22 42 60 64]
[45 40 23 94  1  8 98 82 53 54]
[66 62 42 89 50 98 51 84 65 86]
[40  2 11 27 37 31 21  0 43 37]


In [63]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


for x in np.nditer(arr3):
   print(x) 

1
2
3
4
5
6
7
8


In [65]:
for i in np.nditer(arr2):
    print(i)

40
45
87
34
29
92
45
22
64
36
21
49
24
35
9
83
58
54
14
83
76
56
23
98
56
31
26
72
81
25
46
70
69
19
5
89
27
10
25
28
35
93
62
87
26
61
76
67
98
50
14
58
91
49
57
84
1
54
42
51
4
86
99
31
21
18
22
42
60
64
45
40
23
94
1
8
98
82
53
54
66
62
42
89
50
98
51
84
65
86
40
2
11
27
37
31
21
0
43
37


In [71]:
from collections import defaultdict

D = defaultdict(int)
for i in np.nditer(arr2):
    k = int(i)
    D[k] = D[k] + 1
    
print(D)


defaultdict(<class 'int'>, {40: 3, 45: 3, 87: 2, 34: 1, 29: 1, 92: 1, 22: 2, 64: 2, 36: 1, 21: 3, 49: 2, 24: 1, 35: 2, 9: 1, 83: 2, 58: 2, 54: 3, 14: 2, 76: 2, 56: 2, 23: 2, 98: 4, 31: 3, 26: 2, 72: 1, 81: 1, 25: 2, 46: 1, 70: 1, 69: 1, 19: 1, 5: 1, 89: 2, 27: 2, 10: 1, 28: 1, 93: 1, 62: 2, 61: 1, 67: 1, 50: 2, 91: 1, 57: 1, 84: 2, 1: 2, 42: 3, 51: 2, 4: 1, 86: 2, 99: 1, 18: 1, 60: 1, 94: 1, 8: 1, 82: 1, 53: 1, 66: 1, 65: 1, 2: 1, 11: 1, 37: 2, 0: 1, 43: 1})


In [82]:
# m = 0
# for key,values in D.items():
#     if values

m = int(max(list(D.values())))
n = []
for key, values in D.items():
    if values == m:
        n.append(key)

n

[98]

In [83]:
arr

array([0, 1, 2, 3, 4, 5])

In [84]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [85]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [86]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [87]:
arr.reshape(2,3,order ="C")

array([[0, 1, 2],
       [3, 4, 5]])

In [88]:
arr.reshape(2,3,order ="F")

array([[0, 2, 4],
       [1, 3, 5]])

In [89]:
arr.reshape(2,3,order ="A")

array([[0, 1, 2],
       [3, 4, 5]])

In [91]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr4.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [92]:
arr4.reshape(-1) #flatten a multidimensional array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [94]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [95]:
r = 4
c = 5

In [97]:
c, r

(5, 4)

In [98]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [99]:
mat[r,c]

np.int64(45)

In [100]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [101]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [103]:
mat[:,c]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [104]:
mat[r,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [105]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [106]:
mat[r:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [107]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [108]:
mat[3,-3]

np.int64(37)

In [109]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [114]:
mat[0:10,4:9]

array([[ 4,  5,  6,  7,  8],
       [14, 15, 16, 17, 18],
       [24, 25, 26, 27, 28],
       [34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48],
       [54, 55, 56, 57, 58],
       [64, 65, 66, 67, 68],
       [74, 75, 76, 77, 78],
       [84, 85, 86, 87, 88],
       [94, 95, 96, 97, 98]])

In [110]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [115]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [119]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [120]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [121]:
mat[2:6, 2:7]

array([[22, 23, 24, 25, 26],
       [32, 33, 34, 35, 36],
       [42, 43, 44, 45, 46],
       [52, 53, 54, 55, 56]])

In [122]:
mat[1:6, 5:9]

array([[15, 16, 17, 18],
       [25, 26, 27, 28],
       [35, 36, 37, 38],
       [45, 46, 47, 48],
       [55, 56, 57, 58]])

In [123]:
#masking
id(mat)

2276246389648

In [124]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [129]:
mat[mat<79]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78])

In [130]:
mat[mat>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
       82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
       99])

In [131]:
mat[mat == 50]

array([50])

In [133]:
a1 = mat[mat < 50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])