### Complete Numpy Documentation

1. Array Creation Function 

In [1]:
import numpy as np

In [3]:
#array from a list

a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
#array with evenly spaced values
b = np.arange(0,30,4.2)
print("Array b:", b) 

Array b: [ 0.   4.2  8.4 12.6 16.8 21.  25.2 29.4]


In [12]:
c = np.linspace(0,54,19) #5 values evenly spaced between 0 and 1
print("Array c:", c)

Array c: [ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36. 39. 42. 45. 48. 51.
 54.]


In [24]:
np.zeros((5,4,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [26]:
e = np.ones((3,4,5))
e

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [32]:
#create a identity matrix

f = np.eye((4))
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

2. Array Manipulation Funcitons

In [38]:
#Reshape an array

a1 = np.arange(0,10)
reshaped = np.reshape(a1,(2,5))
reshaped

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
#Flatten an array

f1 = np.random.randint(1,100, (2,2))
flattened = np.ravel(f1)
flattened

array([64, 64, 77, 78], dtype=int32)

In [48]:
#transpose an arrat

e1 = np.random.randint(1,100, (3,3))
e1

array([[40, 90, 96],
       [48, 40, 44],
       [40, 46, 90]], dtype=int32)

In [51]:
transposed = np.transpose(e1)
transposed

array([[40, 48, 40],
       [90, 40, 46],
       [96, 44, 90]], dtype=int32)

In [52]:
# Stack arrays vertically 
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2])
stacked

array([[1, 2],
       [3, 4]])

3. Mathematical Funcitons

In [54]:
#Add two arrays

g = np.array([1,2,3,4])
added = np.add(g,2) #add 2 to each element
added

array([3, 4, 5, 6])

In [57]:
#Square root of each element 

sqrt_val = np.sqrt(g) #Square root of each element
sqrt_val

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [58]:
print(a1,g)

[0 1 2 3 4 5 6 7 8 9] [1 2 3 4]


In [63]:
a1 = np.random.randint(2,100,(4,3))
b1 = np.random.randint(2,100,(3,4))
np.dot(a1,b1)

array([[ 3726,  5177,  4859,  8006],
       [ 6463,  9870, 11055, 15646],
       [ 7093, 11437, 13608, 18264],
       [ 3871,  4590,  4315,  7287]], dtype=int32)

4. Statistical Funcitons

In [67]:
s = np.array([1,2,3,4])
mean  = np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [69]:
# Standard deviation of an array

std_dev = np.std(s)
std_dev

np.float64(1.118033988749895)

In [70]:
#minimum element of an array
minimum = np.min(s)
minimum

np.int64(1)

In [71]:
#Maximum of an array
maximum = np.max(s)
maximum

np.int64(4)

5. Linear Algebra Funcitons

In [72]:
#Create a matrix 

matrix = np.array([[1,2],[3,4]])

In [73]:
#determinant of a matrix 

determinant = np.linalg.det(matrix)
print("Determinant of a matrix:",determinant)

Determinant of a matrix: -2.0000000000000004


In [79]:
#Inverse of a matrix 

inverse = np.linalg.inv(matrix)
inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [81]:
inverse = inverse.astype(int)
np.dot(matrix, inverse)

array([[1, 0],
       [1, 0]])

6. Random Sampling Function

In [83]:
#Generate random values between 0 and 1

random_vals = np.random.rand(3)
random_vals

array([0.34856873, 0.66804809, 0.97211219])

In [ ]:
#Set seed for reproductibility
np.random.seed(0)

#Generate random values between 0 and 1

random_vals = np.random.rand(3) 
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [88]:
#Generate Random Integers 
rand_ints = np.random.randint(0,10, size = 5)
rand_ints

array([2, 4, 7, 6, 8], dtype=int32)

In [90]:
#set seed for reproducibility

np.random.seed(0)

#Generate random integers

rand_ints = np.random.randint(0,10,size = 5)
rand_ints

array([5, 0, 3, 3, 7], dtype=int32)

7. Boolean & Logical Functions

In [93]:
# Check if all elements are True
# all

logical_test = np.array([True, False, True])
all_true = np.all(logical_test) #check if all are true
all_true

np.False_

In [95]:
#Check if all elements are True

logical_test = np.array([False, False, False])
all_true = np.all(logical_test)
all_true

np.False_

In [96]:
#Check if any elements are True

any_true = np.any(logical_test)
any_true

np.False_

8. Set Operations