# 3rd February, 2025

In [1]:
range(5)

range(0, 5)

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
r = range(10)
r

range(0, 10)

In [5]:
for i in r:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [7]:
list(range(10,49, 5))

[10, 15, 20, 25, 30, 35, 40, 45]

In [9]:
#max three argument in range

list(range(10, 40, 6,9))

TypeError: range expected at most 3 arguments, got 4

In [11]:
r1 = range(10,40,5)
list((r1))

[10, 15, 20, 25, 30, 35]

In [ ]:
#NumPy

#arrays = tables = rows * columns
#1D array
#2D array
#3D array
#nD array

#Numoy package | numpy library | numpy tools | numpy framework 
#= mathematics + data structure + statistical 


In [12]:
import numpy as np 

np.__version__

'2.2.0'

In [13]:
import sys
sys.version 

'3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]'

In [16]:
my_list = list(range(6))
my_list

[0, 1, 2, 3, 4, 5]

In [17]:
type(my_list)

list

In [19]:
#list to array

arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [20]:
type(arr)

numpy.ndarray

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [28]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
#1st argument < 2nd argument always
np.arange(20,10)

array([], dtype=int64)

In [30]:
np.arange(-20, 10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [31]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [33]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [34]:
np.arange(10,10)

array([], dtype=int64)

In [35]:
np.arange(10,30,5)

array([10, 15, 20, 25])