# 3rd February, 2025

In [1]:
range(5)

range(0, 5)

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
r = range(10)
r

range(0, 10)

In [4]:
for i in r:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [5]:
list(range(10,49, 5))

[10, 15, 20, 25, 30, 35, 40, 45]

In [6]:
#max three argument in range

list(range(10, 40, 6,9))

TypeError: range expected at most 3 arguments, got 4

In [11]:
r1 = range(10,40,5)
list((r1))

[10, 15, 20, 25, 30, 35]

In [ ]:
#NumPy

#arrays = tables = rows * columns
#1D array
#2D array
#3D array
#nD array

#Numoy package | numpy library | numpy tools | numpy framework 
#= mathematics + data structure + statistical 


In [12]:
import numpy as np 

np.__version__

'2.2.0'

In [13]:
import sys
sys.version 

'3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]'

In [16]:
my_list = list(range(6))
my_list

[0, 1, 2, 3, 4, 5]

In [17]:
type(my_list)

list

In [19]:
#list to array

arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [20]:
type(arr)

numpy.ndarray

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [28]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
#1st argument < 2nd argument always
np.arange(20,10)

array([], dtype=int64)

In [30]:
np.arange(-20, 10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [31]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [33]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [34]:
np.arange(10,10)

array([], dtype=int64)

In [35]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [36]:
np.zeros(3)

array([0., 0., 0.])

In [37]:
np.zeros(3,dtype = int) #Parameter tuning

array([0, 0, 0])

In [38]:
np.zeros(4, dtype = bool)

array([False, False, False, False])

In [39]:
np.zeros((2,2),dtype = int)

array([[0, 0],
       [0, 0]])

In [41]:
np.zeros((3,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [43]:
np.zeros((2,10), dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [45]:
np.zeros((10,30), dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [48]:
np.ones(3, dtype= int)

array([1, 1, 1])

In [52]:
4 * np.ones((4,4), dtype = int)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [54]:
np.twos(2,3)

AttributeError: module 'numpy' has no attribute 'twos'

In [57]:
rand(3,2)

NameError: name 'rand' is not defined

In [59]:
random.rand(3,2)

AttributeError: module 'random' has no attribute 'rand'

In [60]:
np.random.rand(3,2)

array([[0.32418327, 0.93565049],
       [0.11049177, 0.1137575 ],
       [0.68601987, 0.95395105]])

In [64]:
5 * np.random.rand(6)

array([4.27487441, 4.15891181, 2.70643897, 4.39011977, 2.83478544,
       2.13419304])

In [68]:
np.random.rand(10)

array([0.89121287, 0.36117772, 0.04186662, 0.05113144, 0.62066798,
       0.63358172, 0.83020966, 0.20094063, 0.93540126, 0.87847364])

In [69]:
np.random.rand(2,4)

array([[0.04885591, 0.16315765, 0.06252624, 0.86844573],
       [0.12552551, 0.910778  , 0.0515321 , 0.60926567]])

In [75]:
np.random.randint(1,10)

9

In [78]:
np.random.randint(2,20)

15

In [79]:
np.random.randint(10,50,5)

array([31, 24, 15, 38, 47], dtype=int32)

In [80]:
np.random.randint(1,6,4)

array([5, 2, 3, 5], dtype=int32)

In [81]:
np.random.randint(-30,20,10)

array([-12, -20,  -4,   3,  11,  12,  -8, -17, -20, -23], dtype=int32)